name: Run Flask and Selenium App

on:
  push:
    branches:
      - main  # می‌توانید شاخه دلخواه خود را مشخص کنید
  workflow_dispatch:  # برای اجرای دستی

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # نسخه پایتون مورد نظر

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run the Flask App
      run: |
        export PATH=$PATH:/usr/local/bin
        python your_flask_app.py